---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: foldingathome
  name: foldingathome
  namespace: foldingathome
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: foldingathome
  template:
    metadata:
      labels:
        app.kubernetes.io/name: foldingathome
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: foldingathome
      containers:
        - image: beastob/foldingathome-arm64
          name: foldingathome
          ports:
            - containerPort: 7396
              name: http
          resources:
            limits:
              memory: "2Gi"
              cpu: "4"
            requests:
              memory: "500Mi"
              cpu: "2"
          livenessProbe:
            tcpSocket:
              port: 7396
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: FOLD_ANON
              valueFrom:
                configMapKeyRef:
                  name: foldingathome-config
                  key: FOLD_ANON
            - name: FOLD_TEAM
              valueFrom:
                configMapKeyRef:
                  name: foldingathome-config
                  key: FOLD_TEAM
            - name: FOLD_POWER
              valueFrom:
                configMapKeyRef:
                  name: foldingathome-config
                  key: FOLD_POWER
            - name: FOLD_ALLOW_IP
              valueFrom:
                configMapKeyRef:
                  name: foldingathome-config
                  key: FOLD_ALLOW_IP
            - name: FOLD_USER
              valueFrom:
                secretKeyRef:
                  name: foldingathome-secret
                  key: FOLD_USER
            - name: FOLD_PASSKEY
              valueFrom:
                secretKeyRef:
                  name: foldingathome-secret
                  key: FOLD_PASSKEY
