---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: foldingathome
  name: foldingathome
  namespace: foldingathome
spec:
  ports:
    - port: 80
      name: http
      nodePort: 30080
      protocol: TCP
      targetPort: 7396
  selector:
    app: foldingathome
  type: NodePort